version: '3.4'

services:
  api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_HTTPS_PORT: 44328
      FAVODEMEL_CONNECTION_STRING: "Data Source=database;Initial Catalog=FavoDeMelDb;User ID=sa;Password=Ewave@2021;Integrated Security=False;"
      RABBITMQ__URL: "rabbitmq://rabbitmq:5672"
      RABBITMQ__USUARIO: "guest"
      RABBITMQ__SENHA: "guest"
      RABBITMQ__Vhost: "/"      
    ports:
      - "8080:80"
      - "44328:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  database:
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=Ewave@2021
    ports:
      - "1433:1433"

  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_USER: "guest"      
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5672:5672"
      - "15672:15672"